### ISSUE TITLE
No copyright or license?

### ISSUE THREAD

**Issue by chaiken** [bbreslauer/qt-bazel-example#3]
I've put a modified version of qt.bzl in our build system and the Grownups require me to include a copyright/license.   Any thoughts here?

**Comment by bbreslauer** [comment]
I might not get around to adding a LICENSE file for a while, but I'm fine licensing it with the Apache 2.0 license. It may end up copyrighted by me, or Google, I haven't decided yet.

**Comment by chaiken** [comment]
Thanks for the response.    I'll put Apache 2.0 in our copy.

**Comment by justbuchanan** [comment]
FYI I have a project at https://github.com/justbuchanan/bazel_rules_qt that contains some code borrowed from this one. I've had a couple requests to add a license it, so I added an apache 2.0 license file and mentioned your name at the top of the `qt.bzl` file (which contains some of your code). Let me know if there are any issues - I want to make sure I'm doing the right thing w.r.t. licensing and giving you proper credit. Thanks for creating this project!

**Comment by chaiken** [comment]
Thanks for the heads-up, Justin.   As noted above, we adopted the Apache license in our repo as suggested by Bob Breslauer, the original author.   I'm sure that preserving the git history will make it clear enough who originated what.   Thanks for helping to make Bazel more usable!

**Comment by bbreslauer** [comment]
Hi Justin, thanks for the heads up. I'm honestly fine without even being mentioned at the top of your qt.bzl file. I just added an UNLICENSE file to the repo, making this completely free to copy.
